# Generated by Django 4.1.2 on 2022-10-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_method', models.CharField(max_length=20)),
                ('payment_amount', models.IntegerField(default=1)),
                ('payment_Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=1)),
                ('Type', models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('Receipt_Number', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentTotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('ServiceId', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceOffered', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.person')),
                ('Years_of_Experience', models.IntegerField(default=1)),
            ],
            bases=('registration.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.person')),
                ('Address', models.CharField(max_length=50)),
                ('ContactNum', models.CharField(max_length=20)),
            ],
            bases=('registration.person',),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Appointment_reason', models.CharField(max_length=100)),
                ('Appointment_date', models.DateTimeField()),
                ('Services_Offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.services')),
                ('Appointment_DoctorUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.doctor')),
                ('Appointment_PatientUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
    ]
