# Generated by Django 4.1.2 on 2022-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='ServicePrice',
            field=models.IntegerField(default=1),
        ),
    ]
