# Generated by Django 4.1.2 on 2022-10-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_services_serviceprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.person')),
                ('EarnedQuota', models.IntegerField(default=0)),
            ],
            bases=('registration.person',),
        ),
        migrations.AlterField(
            model_name='person',
            name='Type',
            field=models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor'), ('A', 'Admin')], max_length=1),
        ),
    ]
