# Generated by Django 4.1.2 on 2022-10-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_admin_alter_person_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='EarnedQuota',
            new_name='Salary',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_status',
            field=models.BooleanField(default=False),
        ),
    ]
