# Generated by Django 4.1.2 on 2022-10-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_earnedquota_admin_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='Salary',
        ),
        migrations.AddField(
            model_name='admin',
            name='ClinicName',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='services',
            name='AdminFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='DoctorFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_date',
            field=models.DateField(),
        ),
    ]
